Ckeditor style
LastCallMedia/Drupal-Scaffold pull request #5
Opened 2016-09-21 18:16 UTC by claytron5000

This adds a wysiwyg style library and the gulpfile configuration to compile the `wysiwyg.scss` file that imports typography and the Foundation elements. I also added concatenation in the gulpfile. That doesn't need to be there for this functionality. The Foundation styles also stripped out padding within the wysiwyg, I've somewhat crudely put it directly into the import file.

2016-09-22 19:46 UTC, rbayliss commented on gulpconfig.js
> +    {
No need to create a separate config section for this.  Any non-partials in the scss directory will be built automatically.

2016-09-22 19:48 UTC, rbayliss commented on gulpfile.js
> +      if (pack.concat) {
Not sure if this was intentional?  I'm not sure we need to support concatenation of SCSS files, since you can @import them from inside the file.

2016-09-22 19:48 UTC, rbayliss commented on themes/custom/scaffold/scaffold.info.yml
> +ckeditor_stylesheets:
Good find!

2016-09-22 19:52 UTC, rbayliss commented on themes/custom/scaffold/scss/wysiwyg.scss
> +@include foundation-everything();
I don't think we actually want all of foundation here.  I think we just want a few bits.  Maybe something like:

`@include foundation-typography;
@include foundation-button;
@include foundation-table;
@include foundation-thumbnail;
@include foundation-visibility-classes;
@include foundation-float-classes;`

Of course, that's all overrideable on a per-project basis.

2016-09-22 19:53 UTC, rbayliss requested changes
Thanks for the PR!

2016-09-23 14:01 UTC, claytron5000 commented on gulpconfig.js
> +    {
Makes a lot of sense, using partials and non-partials simplifies the set up considerably.

2016-09-23 14:01 UTC, claytron5000 commented on gulpfile.js
> +      if (pack.concat) {
see above, use imports and partials.

2016-09-23 14:02 UTC, claytron5000 commented
I made the changes suggested above.

2016-09-23 14:05 UTC, rbayliss approved these changes

2016-09-23 14:05 UTC, merged

2016-09-23 14:05 UTC, rbayliss commented
Awesome!  This looks great.  Thanks!

2016-09-23 14:27 UTC, rbayliss commented
Just a followup here, I was getting an error compiling the SASS, and it looks like you prefixed the foundation mixins with `$`, which was throwing a fatal error.  They're mixins, not variables, so I removed the `$` in ac39eef052a8c406ea5c2aa7b336038732bbc7ad.

Also, added a test to our Travis build where we actually run the build command so we can catch stuff like this sooner.